//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MDMEntities : DbContext
    {
        public MDMEntities()
            : base("name=MDMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Componente> Componente { get; set; }
        public virtual DbSet<Criterio> Criterio { get; set; }
        public virtual DbSet<Dimension> Dimension { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        [DbFunction("MDMEntities", "ResultadoCriterio")]
        public virtual IQueryable<ResultadoCriterio_Result> ResultadoCriterio(Nullable<int> idUsuario, Nullable<int> numVez)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var numVezParameter = numVez.HasValue ?
                new ObjectParameter("NumVez", numVez) :
                new ObjectParameter("NumVez", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ResultadoCriterio_Result>("[MDMEntities].[ResultadoCriterio](@IdUsuario, @NumVez)", idUsuarioParameter, numVezParameter);
        }
    
        [DbFunction("MDMEntities", "ResultadoEvaluacion")]
        public virtual IQueryable<ResultadoEvaluacion_Result> ResultadoEvaluacion(Nullable<int> idUsuario, Nullable<int> numVez)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var numVezParameter = numVez.HasValue ?
                new ObjectParameter("NumVez", numVez) :
                new ObjectParameter("NumVez", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ResultadoEvaluacion_Result>("[MDMEntities].[ResultadoEvaluacion](@IdUsuario, @NumVez)", idUsuarioParameter, numVezParameter);
        }
    
        [DbFunction("MDMEntities", "ResultadosHistoricos")]
        public virtual IQueryable<ResultadosHistoricos_Result> ResultadosHistoricos(Nullable<int> idUsuaruio)
        {
            var idUsuaruioParameter = idUsuaruio.HasValue ?
                new ObjectParameter("idUsuaruio", idUsuaruio) :
                new ObjectParameter("idUsuaruio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ResultadosHistoricos_Result>("[MDMEntities].[ResultadosHistoricos](@idUsuaruio)", idUsuaruioParameter);
        }
    }
}
