//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int IdRespuesta { get; set; }
        public Nullable<int> IdOpcion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> ContVez { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
