//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Respuesta = new HashSet<Respuesta>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string TipoUsuario { get; set; }
        public string UsuarioIngreso { get; set; }
        public string Clave { get; set; }
        public string Entidad { get; set; }
        public string Cargo { get; set; }
        public Nullable<bool> EncuestaTerminada { get; set; }
        public Nullable<int> NroEcuestasTerminadas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta { get; set; }
    }
}
